version: '3.5'
services:

  postgres:
    container_name: pg_generic
    image: postgres:12.1
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'generic_db'
    volumes:
      - ./.postgresdb/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: on-failure


  pgadmin:
    container_name: pgadmin_generic
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: "shahin.zeynalov95@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: '12345'
    volumes:
      - ./.pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: on-failure

networks:
  postgres:
    driver: bridge
volumes:
    postgres:
    pgadmin:
